#!/bin/bash
#
# Exemplo depois da depuração
# Retornar a média

[ "$#" -eq "0" ] && echo "0" && exit 0

SOMA_NOTAS=$(echo "$@" | tr ' ' '+')

set -xv # Inicia o setor de depuração

echo $(echo "($SOMA_NOTAS)/$#" | bc -l)

set +xv # Fecha o setor de depuração
